[project]
name = "cloudia_app"
version = "0.0.1"

dependencies = [
	"aiohttp",
	"aiomqtt",
	"pydantic",
	"pyyaml",
	"ujson",
	"influxdb-client"
]

[build-system]
requires = [
    "setuptools >= 67.8.0",
    "setuptools_scm >= 7.1.0"
]

[project.scripts]
mqtt-app = "app:main"
